import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { SafetyFooter } from "@/components/SafetyFooter";

export const Route = createFileRoute("/legal")({
  head: () => ({
    meta: [
      { title: "Disclaimers, privacy & terms — Kalm" },
      {
        name: "description",
        content:
          "How Kalm handles sensitive wellness data, what the AI companion is and isn't, and your data rights.",
      },
      { property: "og:title", content: "Disclaimers, privacy & terms — Kalm" },
      {
        property: "og:description",
        content: "What Kalm is, what it isn't, and how your wellness data is handled.",
      },
    ],
  }),
  component: LegalPage,
});

const SECTIONS = [
  {
    heading: "Kalm is not medical care",
    body: "Kalm is a wellness support tool. It does not diagnose, treat, or provide medical advice, and it is not a replacement for therapy, psychiatric care, or emergency services. If you are in crisis, use the crisis resources page or your local emergency number.",
  },
  {
    heading: "How the AI works",
    body: "Conversations are generated by a large language model using the self-introduction and check-in data you choose to share. Every input is screened for crisis language before a normal reply is generated; when crisis language is detected, Kalm interrupts the conversation and shows support resources instead.",
  },
  {
    heading: "Your data",
    body: "Mental health information is sensitive personal data. Kalm stores your profile, check-ins, conversations and session transcripts so your experience stays continuous. You can export or delete your data at any time from Profile settings, with no retention dark patterns.",
  },
  {
    heading: "Age requirement",
    body: "Kalm is for people aged 13 and over. Teen mode applies stricter safety guardrails and age-appropriate content. Kalm is not intended for children under 13.",
  },
  {
    heading: "Workplace accounts",
    body: "If you access Kalm through an employer plan, your employer can only ever see aggregate, anonymized usage statistics. Your conversations, check-ins and session content are never shared with them.",
  },
];

function LegalPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-14">
        <Link
          to="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" aria-hidden />
          Back
        </Link>
        <h1 className="text-4xl">About, disclaimers &amp; privacy</h1>
        <div className="mt-10 space-y-8">
          {SECTIONS.map(({ heading, body }) => (
            <section key={heading}>
              <h2 className="text-xl">{heading}</h2>
              <p className="mt-2 text-muted-foreground">{body}</p>
            </section>
          ))}
        </div>
        <p className="mt-12 text-sm text-muted-foreground">
          Questions about your data? Reach out from Profile settings.{" "}
          <Link to="/crisis" className="font-semibold text-primary underline underline-offset-4">
            Crisis resources
          </Link>
        </p>
      </main>
      <SafetyFooter />
    </div>
  );
}
